name: Deploy to server
on:
  push:
    branches:
      - step3-reusable-workflows
jobs:
  deploy:
    uses: ./.github/workflows/reusable_deploy.yaml
    with:
      container_name: black-lotos-prod
    secrets: 
        HOST_ADDRESS: ${{ secrets.ARTIFACT_HOST }},www.${{ secrets.ARTIFACT_HOST }}
        USER: ${{ secrets.USER }}
        PSWD: ${{ secrets.PSWD }}
        HOST: ${{ secrets.HOST }}
        ARTIFACT_SSH_KEY: ${{ secrets.ARTIFACT_SSH_KEY }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

